### ISSUE TITLE
mpv require XQuartz now and it's mandatory and it's bad

### ISSUE THREAD

**Issue by Xefir** [mpv-player/homebrew-mpv#49]
Hello

Since this commit https://github.com/mpv-player/homebrew-mpv/commit/c677d36c01f84f95e0c3535716fc1a8b44465083 ; mpv require to install XQuartz and I don't want to.
It's because the switch "with-harfbuzz" require the "cairo" dependencie witch require x11 to work.

Can you make a --without-x11 switch or something like that ?
Because there is a --with-x11 switch, but with the commit mentionned earlier, it became useless.

Thanks :-)

**Comment by wm4** [comment]
Isn't this a harfbuzz issue? mpv/libass certainly do not require harfbuzz compiled against cairo or x11.

**Comment by AirPort** [comment]
Cairo itself has a `--without-x11` switch.

**Comment by pigoz** [comment]
I don't we can specify a --without-x11 to cairo from the libass formulas. So I'm just reverting c677d36

**Comment by wm4** [comment]
Wait, isn't the cairo formula just completely broken? Who uses X11 on OSX?

**Comment by pigoz** [comment]
Yes it's probably broken..

**Comment by khaledhosny** [comment]
HarfBuzz does not require Cairo at all, it is the hb-view utility bundled with HarfBuzz that require it. Ideally the HarfBuzz utilities should be a separate package (like in e.g. Debian) or not built  by default (most HarfBuzz users don't even need them).

**Comment by pigoz** [comment]
ok, I will create new harfbuzz package (in this tap) without the requirement

**Comment by pigoz** [comment]
Fixed in 9824bbf8b4b

Though it will still require cairo if you use official libass.

**Comment by habamax** [comment]
It happend again with mpv 0.8.3

**Comment by vitorgalvao** [comment]
@habamax Seems to be due to the homebrew version of harfbuzz being newer, and it trying to use that one. #57 should fix it. Made the changes locally, reinstalled harfbuzz, and the mpv update worked.

**Comment by hashier** [comment]
I installed libass-ct and harfbuzz from this repo.
In `libass-ct` it states:
> depends_on 'mpv-player/mpv/harfbuzz'

When I now run after installing everything it seems like home-brew things (apparently?) that the installed mpv-player/mpv/harfbuzz is the same harfbuzz as the one from home-brew itself which results in the following output:

```
$ brew missing
harfbuzz: cairo
libass-ct: cairo
mpv: cairo
```

Might it possibly worth it to rename harfbuzz like libass-ct has a prefix to be distinguished from the "official" one.

**Comment by pigoz** [comment]
Yes that's a more practical solution (and will also prevent the versions problem to ever popup again).

**Comment by mrkapqa** [comment]
hello can you please help me to compile mpv on wheezy? if requires nowadays "harfbuzz" and says 

configure: error: Either DirectWrite (on Windows), CoreText (on OSX), or Fontconfig(Linux, other) is required. If you really want to compile withouta system font provider, add --disable-require-system-font-provider

but if if i do

./rebuild --disable-require-system-font-provider

is still get same error.  i really need mpv on wheezy because jessie is too new for system. thanks

**Comment by hashier** [comment]
@mrkapqa You ended up in a OS X thread.
This is the mpv home-brew repository, you probably should open a bug on the mpv repository instead.
